# Generated by Django 5.0.8 on 2024-08-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_braskem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroform',
            options={'managed': False},
        ),
    ]
