# Generated by Django 5.0.8 on 2024-08-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_braskem', '0002_alter_cadastroform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroform',
            options={},
        ),
    ]
